package project.kconnecta.user.backend.feature.activity.entity.enums;

public enum ActivityLogType {
    LOGIN,
    LOGOUT,
    REGISTER,
    GOOGLE_LOGIN,
    PASSWORD_CHANGED,
    RESET_PASSWORD,
    POST_CREATED,
    POST_DELETED,
    COMMENT_ADDED,
    REACTION_ADDED,
    POST_SHARED,
    FRIEND_REQUEST_SENT,
    FRIEND_ACCEPTED,
    LOGIN_FAILED,
    COMMENT_CREATED,
    MESSAGE_SENT,
    MESSAGE_BLOCKED_SPAM,
    MESSAGE_BLOCKED_KEYWORD,
    REPORT_CREATED,
    ACCOUNT_LOCKED,
    ACCOUNT_REVIEW_REQUESTED,
    CHAT_RESTRICTED
}
